
//users
export const FOLLOW = 'users/FOLLOW'
export const UN_FOLLOW = 'users/UN_FOLLOW'
export const ADD_MORE_USERS = 'users/ADD_MORE_USERS'
export const CHANGE_CURRENT_PAGE = 'users/CHANGE_CURRENT_PAGE'
export const CHANGE_TOTAL_COUNT = 'users/CHANGE_TOTAL_COUNT'
export const CHANGE_IS_FETCHING_FROM_USERS = 'users/CHANGE_IS_FETCHING_FROM_USERS'
export const SENDING_REQUEST_FROM_FOLLOW_UNFOLLOW = 'users/SENDING_REQUEST_FROM_FOLLOW_UNFOLLOW'
export const SET_CURRENT_PAGE_FROM_USERS = 'users/SET_CURRENT_PAGE_FROM_USERS'
export const SET_PORTION_PAGE_FROM_USERS = 'users/SET_PORTION_PAGE_FROM_USERS'
export const GET_USERS_SAGA = 'users/GET_USERS_SAGA'
export const FOLLOW_UNFOLLOW_SAGA = 'users/FOLLOW_UNFOLLOW_SAGA'
export const UNFOLLOW_SAGA = 'users/UNFOLLOW_SAGA'
export const FOLLOW_SAGA = 'users/FOLLOW_SAGA'

//app
export const INITIALIZE_SAGA = 'app/INITIALIZE_SAGA'
export const SET_INITIALIZED = 'app/SET_INITIALIZED'

//profile
export const ADD_POST = 'profile/ADD_POST'
export const SET_USER_PROFILE = 'profile/SET_USER_PROFILE'
export const CHANGE_IS_FETCHING_FROM_PROFILE = 'profile/CHANGE_IS_FETCHING_FROM_PROFILE'
export const CHANGE_STATUS = 'profile/CHANGE_STATUS'
export const SAVE_PHOTO_FROM_PROFILE = 'profile/SAVE_PHOTO_FROM_PROFILE'
export const IS_OPEN_MENU_FROM_PROFILE = 'profile/IS_OPEN_MENU_FROM_PROFILE'
export const GET_STATUS_FROM_PROFILE_SAGA = 'profile/GET_STATUS_FROM_PROFILE_SAGA'
export const UPDATE_STATUS_FROM_PROFILE_SAGA = 'profile/UPDATE_STATUS_FROM_PROFILE_SAGA'
export const SAVE_PHOTO_FROM_PROFILE_SAGA = 'profile/SAVE_PHOTO_FROM_PROFILE_SAGA'
export const SAVE_NEW_PROFILE_SAGA = 'profile/SAVE_NEW_PROFILE_SAGA'
export const GET_PROFILE_SAGA = 'profile/GET_PROFILE_SAGA'

//auth
export const GET_CAPTCHA_SAGA = 'auth/GET_CAPTCHA_SAGA'
export const SET_AUTH_NETWORK_ERROR = 'auth/SET_AUTH_NETWORK_ERROR'
export const SET_USER_FROM_AUTH_SAGA = 'auth/SET_USER_FROM_AUTH_SAGA'
export const LOGOUT_SAGA = 'auth/LOGOUT_SAGA'
export const LOGIN_SAGA = 'auth/LOGIN_SAGA'
export const SET_USER_DATA = 'auth/SET_USER_DATA'
export const GET_CAPTCHA_URL_SUCCESS = 'auth/GET_CAPTCHA_URL_SUCCESS'

//news
export const GET_NEWS_SAGA = 'news/GET_NEWS_SAGA'
export const SET_NEWS ='news/SET_NEWS'
export const SET_IS_FETCHING ='news/SET_IS_FETCHING'
export const SET_PAGE ='news/SET_PAGE'
export const SET_PAGE_SIZE ='news/SET_PAGE_SIZE'
export const SET_PORTION_NUMBER ='news/SET_PORTION_NUMBER'
